// Starter-library "bundles" UI. Lists the built-in bundles and lets the user
// sync one into their library. When a sync would collide with songs they
// already have (same title + artist), a modal lets them choose per song —
// overwrite the existing one or import as a `_N` duplicate — with an
// apply-to-all shortcut. Sync is available to every user (not admin-gated).

import { useState } from 'react';
import { Library, Download, FileDown } from 'lucide-react';
import { Modal } from '@/components/ui/Modal';
import { importBundle, useAdminMode, useSongs, type BundleImportSummary } from '@/db/repo';
import { listBundles, type SongBundle } from '@/lib/library';
import { planBundleImport, type ConflictResolution, type ImportPlanItem } from '@/lib/library/import';
import type { Song } from '@/types';

/** Build a ready-to-commit bundle module from selected songs (dev tool). */
function bundleModuleText(name: string, description: string, songs: Song[]): string {
  const slug = name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'bundle';
  const camel = slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  const bundle: SongBundle = {
    id: slug,
    name: name.trim() || 'Untitled bundle',
    description: description.trim() || undefined,
    version: 1,
    songs: songs.map((s, i) => ({ ...s, order: i, createdAt: 0, updatedAt: 0 })),
  };
  return (
    `// Generated by the in-app bundle authoring tool (dev only).\n` +
    `// Save under src/lib/library/bundles/ and add ${camel}Bundle to BUNDLES in index.ts.\n` +
    `import type { SongBundle } from '@/lib/library/types';\n\n` +
    `export const ${camel}Bundle: SongBundle = ${JSON.stringify(bundle, null, 2)};\n`
  );
}

function downloadText(filename: string, text: string): void {
  const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' }));
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

export function BundleSettings() {
  const bundles = listBundles();
  const songs = useSongs();
  const admin = useAdminMode();
  // Authoring is dev-only: bundles are static code, so this just exports a module
  // to commit — it can't change the live hosted build.
  const showAuthoring = import.meta.env.DEV && admin;

  const [active, setActive] = useState<SongBundle | null>(null);
  const [plan, setPlan] = useState<ImportPlanItem[]>([]);
  const [resolutions, setResolutions] = useState<Record<string, ConflictResolution>>({});
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<{ name: string; summary: BundleImportSummary } | null>(null);

  const [bundleName, setBundleName] = useState('');
  const [bundleDesc, setBundleDesc] = useState('');
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());

  function toggleSelected(id: string) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function exportBundle() {
    const chosen = (songs ?? []).filter((s) => selectedIds.has(s.id));
    if (!chosen.length) return;
    const slug = bundleName.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'bundle';
    downloadText(`${slug}.ts`, bundleModuleText(bundleName, bundleDesc, chosen));
  }

  const existingRefs = (songs ?? []).map((s) => ({ id: s.id, title: s.title, artist: s.artist }));

  async function runImport(bundle: SongBundle, res: Record<string, ConflictResolution>) {
    setBusy(true);
    try {
      const summary = await importBundle(bundle, res);
      setResult({ name: bundle.name, summary });
    } finally {
      setBusy(false);
      setActive(null);
    }
  }

  function startSync(bundle: SongBundle) {
    const p = planBundleImport(bundle, existingRefs);
    const conflicts = p.filter((i) => i.status === 'conflict');
    if (conflicts.length === 0) {
      void runImport(bundle, {});
      return;
    }
    const initial: Record<string, ConflictResolution> = {};
    conflicts.forEach((i) => (initial[i.song.id] = 'duplicate'));
    setPlan(p);
    setResolutions(initial);
    setActive(bundle);
  }

  function applyToAll(res: ConflictResolution) {
    setResolutions((prev) => {
      const next = { ...prev };
      for (const k of Object.keys(next)) next[k] = res;
      return next;
    });
  }

  const conflicts = plan.filter((i) => i.status === 'conflict');
  const newCount = plan.filter((i) => i.status === 'new').length;

  return (
    <>
    <section className="space-y-3">
      <h2 className="label">Starter library</h2>
      <div className="card divide-y divide-ink-200 dark:divide-ink-800">
        {bundles.map((b) => (
          <div key={b.id} className="flex items-center justify-between gap-3 px-4 py-3">
            <div className="min-w-0">
              <div className="flex items-center gap-2 text-sm font-medium">
                <Library size={15} className="text-ink-400" />
                {b.name}
                <span className="text-xs font-normal text-ink-400">v{b.version}</span>
              </div>
              <p className="mt-0.5 text-xs text-ink-500 dark:text-ink-400">
                {[b.description, `${b.songs.length} song${b.songs.length === 1 ? '' : 's'}`]
                  .filter(Boolean)
                  .join(' · ')}
              </p>
            </div>
            <button className="btn-secondary shrink-0" onClick={() => startSync(b)} disabled={busy}>
              <Download size={15} /> Sync
            </button>
          </div>
        ))}
      </div>

      {result && (
        <p className="text-xs text-ink-500 dark:text-ink-400">
          Synced <strong>{result.name}</strong>: {result.summary.added} added,{' '}
          {result.summary.duplicated} duplicated, {result.summary.overwritten} overwritten
          {result.summary.setlists > 0 ? `, ${result.summary.setlists} setlist(s)` : ''}.
        </p>
      )}

      <Modal
        open={Boolean(active)}
        onClose={() => setActive(null)}
        title={active ? `Sync “${active.name}”` : 'Sync'}
        footer={
          <>
            <button className="btn-ghost" onClick={() => setActive(null)}>
              Cancel
            </button>
            <button
              className="btn-primary"
              disabled={busy}
              onClick={() => active && void runImport(active, resolutions)}
            >
              Import
            </button>
          </>
        }
      >
        <p className="mb-3 text-sm text-ink-600 dark:text-ink-300">
          {newCount > 0 && (
            <>
              <strong>{newCount}</strong> new song{newCount === 1 ? '' : 's'} will be added.{' '}
            </>
          )}
          <strong>{conflicts.length}</strong> already exist{conflicts.length === 1 ? 's' : ''} with
          the same title &amp; artist. Choose what to do with each:
        </p>

        <div className="mb-3 flex items-center gap-2 text-xs">
          <span className="text-ink-500">Apply to all:</span>
          <button className="chip" onClick={() => applyToAll('overwrite')}>
            Overwrite
          </button>
          <button className="chip" onClick={() => applyToAll('duplicate')}>
            Duplicate
          </button>
        </div>

        <ul className="space-y-2">
          {conflicts.map((i) => (
            <li
              key={i.song.id}
              className="flex items-center justify-between gap-3 rounded-lg border border-ink-200 px-3 py-2 dark:border-ink-800"
            >
              <span className="min-w-0 truncate text-sm">
                {i.song.title}
                {i.song.artist ? <span className="text-ink-400"> · {i.song.artist}</span> : null}
              </span>
              <select
                className="input h-8 w-auto py-0 text-sm"
                value={resolutions[i.song.id] ?? 'duplicate'}
                onChange={(e) =>
                  setResolutions((prev) => ({
                    ...prev,
                    [i.song.id]: e.target.value as ConflictResolution,
                  }))
                }
              >
                <option value="duplicate">Import as duplicate</option>
                <option value="overwrite">Overwrite existing</option>
              </select>
            </li>
          ))}
        </ul>
      </Modal>
    </section>

    {showAuthoring && (
      <section className="space-y-3">
        <h2 className="label">Author a bundle (dev)</h2>
        <div className="card space-y-3 p-4">
          <p className="text-xs text-ink-500 dark:text-ink-400">
            Pick songs from your library and download a bundle module. Commit it under{' '}
            <code>src/lib/library/bundles/</code> and add it to <code>index.ts</code>. This is a
            developer workflow — it never changes the live hosted app.
          </p>
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
            <input
              className="input"
              placeholder="Bundle name"
              value={bundleName}
              onChange={(e) => setBundleName(e.target.value)}
            />
            <input
              className="input"
              placeholder="Description (optional)"
              value={bundleDesc}
              onChange={(e) => setBundleDesc(e.target.value)}
            />
          </div>
          {songs && songs.length > 0 ? (
            <div className="max-h-60 space-y-1 overflow-y-auto rounded-lg border border-ink-200 p-2 dark:border-ink-800">
              {songs.map((s) => (
                <label key={s.id} className="flex items-center gap-2 px-1 py-0.5 text-sm">
                  <input
                    type="checkbox"
                    className="accent-accent"
                    checked={selectedIds.has(s.id)}
                    onChange={() => toggleSelected(s.id)}
                  />
                  <span className="truncate">
                    {s.title}
                    {s.artist ? <span className="text-ink-400"> · {s.artist}</span> : null}
                  </span>
                </label>
              ))}
            </div>
          ) : (
            <p className="text-xs text-ink-400">Add some songs first.</p>
          )}
          <button className="btn-secondary" onClick={exportBundle} disabled={selectedIds.size === 0}>
            <FileDown size={15} /> Download bundle module ({selectedIds.size})
          </button>
        </div>
      </section>
    )}
    </>
  );
}
